server:
  port: 8081

spring:
  application:
    name: course-service

  zipkin:
    enabled: false
  sleuth:
    enabled: false

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

  jpa:
    properties:
      hibernate:
        dialect: ${datasource.dialect}
        connection:
          characterEncoding: UTF-8
          CharSet: UTF-8
          useUnicode: true
    show-sql: true
    hibernate:
      ddl-auto: none

  config:
    import: optional:configserver:http://localhost:8086

  profiles:
    active: prod

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose tất cả các endpoint bao gồm refresh
      health:
        show-details: always
    endpoint:
      refresh:
        enabled: true  # Bật endpoint refresh

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
